import React from 'react';
import './service.css';
import {Link} from 'react-router-dom';
function Service() {
    return (
      <div>
        <header>
        <h1>Smart Classroom Management System</h1>
      </header>
      <nav>
        <ul>
          <li><a href="/home">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/service">Services</a></li>
          <li className="dropdown">
            <a href="#login">Login</a>
            <ul className="sub-menu">
              <li><Link to="/studregister">Student Login</Link></li>
              <li><Link to="/facultyregister">Faculty Login</Link></li>
              <li><a href="#">Admin Login</a></li>
            </ul>
          </li>
        </ul>
      </nav>
        <div className="services-container">
      <h2 className="services-heading">Services</h2>
      <div className="services-grid">
        <div className="service-box">
          <div className="icon">🔐</div>
          <h3>Authentication Code</h3>
          <p>
            A unique authentication code will be generated by the faculty to
            save the system from any student fraudulent activities.
          </p>
        </div>
        <div className="service-box">
          <div className="icon">📝</div>
          <h3>Generating Attendance Sheet</h3>
          <p>
            As soon as the face will be scanned, the attendance of the student
            will be marked in the attendance sheet.
          </p>
        </div>
        <div className="service-box">
          <div className="icon">⏳</div>
          <h3>Time Saving</h3>
          <p>
            The image is scanned in just a few seconds, resulting in saving time
            compared to the offline attendance system.
          </p>
        </div>
      </div>
      </div>
    </div>
    );
}
export default Service;